version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: rbac-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    networks:
      - rbac-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rbac-backend
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://localhost:8080/realms/rbac-realm
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/rbac-realm/protocol/openid-connect/certs
    ports:
      - "8081:8081"
    depends_on:
      - keycloak
    networks:
      - rbac-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rbac-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - WDS_SOCKET_PORT=0
    networks:
      - rbac-net

networks:
  rbac-net:
    driver: bridge
