server:
  port: 8081

spring:
  application:
    name: rbac-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/rbac-realm
          jwk-set-uri: http://localhost:8080/realms/rbac-realm/protocol/openid-connect/certs
